config/routes.rb
Rails.application.routes.draw do
  resources :thirdmodels

  resources :secondmodels

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/secondmodel.rb
class Secondmodel < ActiveRecord::Base
end

app/models/thirdmodel.rb
class Thirdmodel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/secondmodels_controller.rb
class SecondmodelsController < ApplicationController
  before_action :set_secondmodel, only: [:show, :edit, :update, :destroy]

  # GET /secondmodels
  # GET /secondmodels.json
  def index
    @secondmodels = Secondmodel.all
  end

  # GET /secondmodels/1
  # GET /secondmodels/1.json
  def show
  end

  # GET /secondmodels/new
  def new
    @secondmodel = Secondmodel.new
  end

  # GET /secondmodels/1/edit
  def edit
  end

  # POST /secondmodels
  # POST /secondmodels.json
  def create
    @secondmodel = Secondmodel.new(secondmodel_params)

    respond_to do |format|
      if @secondmodel.save
        format.html { redirect_to @secondmodel, notice: 'Secondmodel was successfully created.' }
        format.json { render :show, status: :created, location: @secondmodel }
      else
        format.html { render :new }
        format.json { render json: @secondmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondmodels/1
  # PATCH/PUT /secondmodels/1.json
  def update
    respond_to do |format|
      if @secondmodel.update(secondmodel_params)
        format.html { redirect_to @secondmodel, notice: 'Secondmodel was successfully updated.' }
        format.json { render :show, status: :ok, location: @secondmodel }
      else
        format.html { render :edit }
        format.json { render json: @secondmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondmodels/1
  # DELETE /secondmodels/1.json
  def destroy
    @secondmodel.destroy
    respond_to do |format|
      format.html { redirect_to secondmodels_url, notice: 'Secondmodel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondmodel
      @secondmodel = Secondmodel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondmodel_params
      params.require(:secondmodel).permit(:name, :phone)
    end
end

app/controllers/thirdmodels_controller.rb
class ThirdmodelsController < ApplicationController
  before_action :set_thirdmodel, only: [:show, :edit, :update, :destroy]

  # GET /thirdmodels
  # GET /thirdmodels.json
  def index
    @thirdmodels = Thirdmodel.all
  end

  # GET /thirdmodels/1
  # GET /thirdmodels/1.json
  def show
  end

  # GET /thirdmodels/new
  def new
    @thirdmodel = Thirdmodel.new
  end

  # GET /thirdmodels/1/edit
  def edit
  end

  # POST /thirdmodels
  # POST /thirdmodels.json
  def create
    @thirdmodel = Thirdmodel.new(thirdmodel_params)

    respond_to do |format|
      if @thirdmodel.save
        format.html { redirect_to @thirdmodel, notice: 'Thirdmodel was successfully created.' }
        format.json { render :show, status: :created, location: @thirdmodel }
      else
        format.html { render :new }
        format.json { render json: @thirdmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thirdmodels/1
  # PATCH/PUT /thirdmodels/1.json
  def update
    respond_to do |format|
      if @thirdmodel.update(thirdmodel_params)
        format.html { redirect_to @thirdmodel, notice: 'Thirdmodel was successfully updated.' }
        format.json { render :show, status: :ok, location: @thirdmodel }
      else
        format.html { render :edit }
        format.json { render json: @thirdmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thirdmodels/1
  # DELETE /thirdmodels/1.json
  def destroy
    @thirdmodel.destroy
    respond_to do |format|
      format.html { redirect_to thirdmodels_url, notice: 'Thirdmodel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thirdmodel
      @thirdmodel = Thirdmodel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thirdmodel_params
      params.require(:thirdmodel).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/secondmodels_helper.rb
module SecondmodelsHelper
end

app/helpers/thirdmodels_helper.rb
module ThirdmodelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/secondmodels/_form.html.erb
<%= form_for(@secondmodel) do |f| %>
  <% if @secondmodel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secondmodel.errors.count, "error") %> prohibited this secondmodel from being saved:</h2>

      <ul>
      <% @secondmodel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secondmodels/edit.html.erb
<h1>Editing Secondmodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @secondmodel %> |
<%= link_to 'Back', secondmodels_path %>

app/views/secondmodels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Secondmodels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secondmodels.each do |secondmodel| %>
      <tr>
        <td><%= secondmodel.name %></td>
        <td><%= secondmodel.phone %></td>
        <td><%= link_to 'Show', secondmodel %></td>
        <td><%= link_to 'Edit', edit_secondmodel_path(secondmodel) %></td>
        <td><%= link_to 'Destroy', secondmodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secondmodel', new_secondmodel_path %>

app/views/secondmodels/new.html.erb
<h1>New Secondmodel</h1>

<%= render 'form' %>

<%= link_to 'Back', secondmodels_path %>

app/views/secondmodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @secondmodel.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @secondmodel.phone %>
</p>

<%= link_to 'Edit', edit_secondmodel_path(@secondmodel) %> |
<%= link_to 'Back', secondmodels_path %>

app/views/thirdmodels/_form.html.erb
<%= form_for(@thirdmodel) do |f| %>
  <% if @thirdmodel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thirdmodel.errors.count, "error") %> prohibited this thirdmodel from being saved:</h2>

      <ul>
      <% @thirdmodel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thirdmodels/edit.html.erb
<h1>Editing Thirdmodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @thirdmodel %> |
<%= link_to 'Back', thirdmodels_path %>

app/views/thirdmodels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thirdmodels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thirdmodels.each do |thirdmodel| %>
      <tr>
        <td><%= thirdmodel.name %></td>
        <td><%= link_to 'Show', thirdmodel %></td>
        <td><%= link_to 'Edit', edit_thirdmodel_path(thirdmodel) %></td>
        <td><%= link_to 'Destroy', thirdmodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thirdmodel', new_thirdmodel_path %>

app/views/thirdmodels/new.html.erb
<h1>New Thirdmodel</h1>

<%= render 'form' %>

<%= link_to 'Back', thirdmodels_path %>

app/views/thirdmodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thirdmodel.name %>
</p>

<%= link_to 'Edit', edit_thirdmodel_path(@thirdmodel) %> |
<%= link_to 'Back', thirdmodels_path %>